PermitRootLogin no
PasswordAuthentication no
AllowUsers pimlog
X11Forwarding no
AllowTcpForwarding no
AllowAgentForwarding no
HostKey /etc/pim/ssh/ssh_host_ed25519_key
HostKey /etc/pim/ssh/ssh_host_rsa_key
Match User pimlog
    ForceCommand /usr/local/bin/pim-log-cat.sh
