import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { resolve } from 'node:path';

const files = [
  'src/client-web/src/api/calendar.ts',
  'src/client-web/src/api/client.ts',
  'src/client-web/src/components/ai/AiRequestDetailPanel.tsx',
  'src/client-web/src/components/ai/AiRequestLogTable.tsx',
  'src/client-web/src/components/ai/AiStatusPanel.tsx',
  'src/client-web/src/components/ai/AiUsageOverview.tsx',
  'src/client-web/src/components/pc-tracker/KeyboardHeatmap.tsx',
  'src/client-web/src/pages/StatusPage.tsx',
  'src/Pim.Api/Endpoints/AiEndpoints.cs',
  'src/Pim.Api/Endpoints/AuthEndpoints.cs',
  'src/Pim.Api/Endpoints/OperationsEndpoints.cs',
  'src/Pim.Api/Endpoints/TodayEndpoints.cs',
  'src/Pim.Api/Middleware/ExceptionMiddleware.cs',
  'src/Pim.Api/Today/TodaySectionService.cs',
  'src/Pim.Core/Ai/AiDtos.cs',
  'src/Pim.Infrastructure/Ai/AiGateway.cs',
  'src/modules/Pim.Module.Files/FilesModule.cs',
  'src/modules/Pim.Module.Files/Services/FileIndexingService.cs',
  'src/modules/Pim.Module.Files/Services/FileOperationService.cs',
  'src/modules/Pim.Module.Files/Services/FileProviderBindingService.cs',
  'src/modules/Pim.Module.Calendar/CalendarModule.cs',
  'src/modules/Pim.Module.Calendar/Services/CalendarRecycleBinService.cs',
  'src/modules/Pim.Module.Calendar/Services/CalendarService.cs',
  'src/modules/Pim.Module.Calendar/Services/OutlookSyncService.cs',
  'src/modules/Pim.Module.QuickNotes/QuickNotesModule.cs',
  'src/modules/Pim.Module.QuickNotes/Services/QuickNoteAttachmentService.cs',
  'src/modules/Pim.Module.QuickNotes/Services/QuickNoteService.cs',
  'src/modules/Pim.Module.PcTracker/PcTrackerModule.cs',
] as const;

const source = files
  .map(file => `${file}\n${readFileSync(resolve(file), 'utf8')}`)
  .join('\n\n');

function escapeRegExp(value: string) {
  return value.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
}

const forbiddenVisiblePatterns = [
  /Export failed/,
  /Import failed/,
  /Session expired/,
  /label="Provider"/,
  /label="Prompt Tokens"/,
  /label="Completion Tokens"/,
  /label="Total Tokens"/,
  /title="Messages"/,
  /title="Request Payload"/,
  /title="Response Text"/,
  /title="Response Raw"/,
  /title="Parsed JSON"/,
  /title="Schema Errors"/,
  />Tokens</,
  />Overall</,
  />Mouse</,
  /Internal server error/,
  /Today section not found/,
  /This Today section is temporarily unavailable/,
  /AI request log not found/,
  /Invalid AI request status/,
  /AI provider is unavailable/,
  /AI request timed out/,
  /AI is disabled/,
  /AI response did not match/,
  /Not authenticated/,
  /Calendar not found/,
  /Event not found/,
  /Task not found/,
  /Restore the parent book first/,
  /Unsupported recycle bin type/,
  /File provider not found/,
  /File item not found/,
  /File version not found/,
  /File suggestion not found/,
  /Multipart form data is required/,
  /Provider id is required/,
  /Upload path is required/,
  /Upload file is required/,
  /Trash id is required/,
  /Destination path must include/,
  /Folders cannot be downloaded/,
  /Folders cannot be indexed/,
  /Unsupported MIME type/,
  /No text extracted/,
  /Quick note not found/,
  /Invalid quick note status/,
  /Attachment file name is required/,
  /Attachment size cannot be negative/,
  /Attachment not found/,
  /Attachment cannot be bound/,
  /Expected multipart\/form-data/,
  /Invalid multipart\/form-data/,
  /No file field/,
  /Outlook not connected/,
  /Confirmation not found/,
  /Confirmation not yet confirmed/,
  /No default calendar found/,
  /restore-as-copy is only supported/,
  /Restore has conflicts/,
  /Ok\("(?:deleted|moved|synced|restored|ok|rejected)"\)/,
  /not found or builtin/,
  /not found/,
];

for (const pattern of forbiddenVisiblePatterns) {
  assert.equal(
    pattern.test(source),
    false,
    `source should not expose untranslated UI text matching: ${pattern}`,
  );
}

const requiredChineseText = [
  '导出失败',
  '导入失败',
  '登录已过期',
  '服务商',
  '输入 Token',
  '输出 Token',
  '总 Token',
  '消息列表',
  '请求载荷',
  '响应文本',
  '原始响应',
  '解析后的 JSON',
  '结构校验错误',
  '总体状态',
  '鼠标',
  '内部服务器错误',
  '今日模块不存在',
  '此今日模块暂时不可用',
  'AI 请求日志不存在',
  'AI 请求状态无效',
  'AI 服务商不可用',
  'AI 请求超时',
  'AI 已禁用',
  'AI 响应不符合要求的格式',
  '未登录',
  '日历不存在',
  '日程不存在',
  '任务不存在',
  '请先恢复所属本',
  '不支持的回收站类型',
  '文件来源不存在',
  '文件不存在',
  '文件版本不存在',
  '文件建议不存在',
  '需要 multipart 表单数据',
  '需要文件来源 ID',
  '需要上传路径',
  '需要上传文件',
  '需要回收站 ID',
  '目标路径必须包含',
  '文件夹不能通过此接口下载',
  '文件夹不能建立索引',
  '不支持的 MIME 类型',
  '未提取到文本',
  '快速记录不存在',
  '快速记录状态无效',
  '附件文件名不能为空',
  '附件大小不能为负数',
  '附件不存在',
  '附件不能绑定到这条快速记录',
  '需要 multipart/form-data 请求',
  'multipart/form-data 请求无效',
  '缺少 file 文件字段',
  'Outlook 未连接',
  '操作确认不存在',
  '操作尚未确认',
  '未找到默认日历',
  '仅日程和任务支持恢复为副本',
  '恢复存在冲突',
  '已删除',
  '已移动',
  '已同步',
  '已恢复',
  '已接收',
  '已拒绝',
  '不存在或为内置项',
  '不存在',
];

for (const text of requiredChineseText) {
  assert.match(source, new RegExp(escapeRegExp(text)), `source should include Chinese UI text: ${text}`);
}
