using Microsoft.EntityFrameworkCore;
using Pim.Infrastructure.Data;

namespace Pim.Module.PcTracker.Services;

public sealed class PcTrackerSchemaInitializer
{
    public const string SchemaSql = """
CREATE TABLE IF NOT EXISTS pc_aw_buckets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pim_device_id VARCHAR(64) NOT NULL,
    aw_device_id VARCHAR(128),
    bucket_id VARCHAR(256) NOT NULL,
    name VARCHAR(256),
    type VARCHAR(64) NOT NULL,
    client VARCHAR(128) NOT NULL,
    hostname VARCHAR(128) NOT NULL,
    created_at_source TIMESTAMPTZ,
    last_updated_source TIMESTAMPTZ,
    data_json JSONB NOT NULL DEFAULT '{{}}'::jsonb,
    seen_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE UNIQUE INDEX IF NOT EXISTS ux_pc_aw_buckets_device_bucket ON pc_aw_buckets (pim_device_id, bucket_id);
CREATE INDEX IF NOT EXISTS ix_pc_aw_buckets_type ON pc_aw_buckets (type);
CREATE INDEX IF NOT EXISTS ix_pc_aw_buckets_seen_at ON pc_aw_buckets (seen_at);
CREATE TABLE IF NOT EXISTS pc_aw_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    device_id VARCHAR(64) NOT NULL,
    timestamp TIMESTAMPTZ NOT NULL,
    duration DOUBLE PRECISION NOT NULL,
    event_type VARCHAR(16) NOT NULL DEFAULT 'window',
    app_name VARCHAR(256),
    window_title TEXT,
    afk_status VARCHAR(16),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    aw_device_id VARCHAR(128),
    aw_hostname VARCHAR(128),
    bucket_id VARCHAR(256),
    bucket_type VARCHAR(64),
    bucket_client VARCHAR(128),
    source_event_id BIGINT,
    data_json JSONB NOT NULL DEFAULT '{{}}'::jsonb,
    app_name_normalized VARCHAR(256),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS ix_pc_aw_events_device_id ON pc_aw_events (device_id);
CREATE INDEX IF NOT EXISTS ix_pc_aw_events_timestamp ON pc_aw_events (timestamp);
CREATE INDEX IF NOT EXISTS ix_pc_aw_events_event_type ON pc_aw_events (event_type);
ALTER TABLE pc_aw_events ADD COLUMN IF NOT EXISTS aw_device_id VARCHAR(128);
ALTER TABLE pc_aw_events ADD COLUMN IF NOT EXISTS aw_hostname VARCHAR(128);
ALTER TABLE pc_aw_events ADD COLUMN IF NOT EXISTS bucket_id VARCHAR(256);
ALTER TABLE pc_aw_events ADD COLUMN IF NOT EXISTS bucket_type VARCHAR(64);
ALTER TABLE pc_aw_events ADD COLUMN IF NOT EXISTS bucket_client VARCHAR(128);
ALTER TABLE pc_aw_events ADD COLUMN IF NOT EXISTS source_event_id BIGINT;
ALTER TABLE pc_aw_events ADD COLUMN IF NOT EXISTS data_json JSONB NOT NULL DEFAULT '{{}}'::jsonb;
ALTER TABLE pc_aw_events ADD COLUMN IF NOT EXISTS app_name_normalized VARCHAR(256);
ALTER TABLE pc_aw_events ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW();
CREATE INDEX IF NOT EXISTS ix_pc_aw_events_bucket_id ON pc_aw_events (bucket_id);
CREATE INDEX IF NOT EXISTS ix_pc_aw_events_source_event_id ON pc_aw_events (source_event_id);
CREATE INDEX IF NOT EXISTS ix_pc_aw_events_app_name_normalized ON pc_aw_events (app_name_normalized);
CREATE UNIQUE INDEX IF NOT EXISTS ux_pc_aw_events_source ON pc_aw_events (device_id, bucket_id, source_event_id) WHERE bucket_id IS NOT NULL AND source_event_id IS NOT NULL;
CREATE TABLE IF NOT EXISTS pc_keystats_samples (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pim_device_id VARCHAR(64) NOT NULL,
    sampled_at_utc TIMESTAMPTZ NOT NULL,
    stats_date DATE NOT NULL,
    stats_timezone_offset_minutes INT NOT NULL,
    key_presses INT NOT NULL DEFAULT 0,
    left_clicks INT NOT NULL DEFAULT 0,
    right_clicks INT NOT NULL DEFAULT 0,
    middle_clicks INT NOT NULL DEFAULT 0,
    side_back_clicks INT NOT NULL DEFAULT 0,
    side_forward_clicks INT NOT NULL DEFAULT 0,
    mouse_distance DOUBLE PRECISION NOT NULL DEFAULT 0,
    scroll_distance DOUBLE PRECISION NOT NULL DEFAULT 0,
    peak_kps INT NOT NULL DEFAULT 0,
    peak_cps INT NOT NULL DEFAULT 0,
    formatted_mouse_distance VARCHAR(64),
    formatted_scroll_distance VARCHAR(64),
    key_counts_json JSONB NOT NULL DEFAULT '{{}}'::jsonb,
    app_stats_json JSONB NOT NULL DEFAULT '{{}}'::jsonb,
    raw_json JSONB NOT NULL DEFAULT '{{}}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE UNIQUE INDEX IF NOT EXISTS ux_pc_keystats_samples_device_minute ON pc_keystats_samples (pim_device_id, sampled_at_utc);
CREATE INDEX IF NOT EXISTS ix_pc_keystats_samples_stats_date ON pc_keystats_samples (stats_date);
CREATE TABLE IF NOT EXISTS pc_app_categories (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    app_pattern VARCHAR(128) NOT NULL,
    category_name VARCHAR(64) NOT NULL,
    color VARCHAR(7) DEFAULT '#6B5EE4',
    priority INT DEFAULT 0,
    is_builtin BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMPTZ DEFAULT NOW()
);
CREATE TABLE IF NOT EXISTS pc_activity_category_rules (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    rule_name VARCHAR(128) NOT NULL,
    scope VARCHAR(16) NOT NULL DEFAULT 'activity',
    category_name VARCHAR(64),
    project_tag VARCHAR(128),
    color VARCHAR(7) NOT NULL DEFAULT '#64748b',
    priority INT NOT NULL DEFAULT 0,
    source VARCHAR(32) NOT NULL DEFAULT 'user',
    status VARCHAR(16) NOT NULL DEFAULT 'active',
    conditions_json JSONB NOT NULL DEFAULT '{{}}'::jsonb,
    confidence DOUBLE PRECISION NOT NULL DEFAULT 1,
    explanation TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS ix_pc_activity_category_rules_status ON pc_activity_category_rules (status);
CREATE INDEX IF NOT EXISTS ix_pc_activity_category_rules_priority ON pc_activity_category_rules (priority);
CREATE INDEX IF NOT EXISTS ix_pc_activity_category_rules_category_name ON pc_activity_category_rules (category_name);
CREATE INDEX IF NOT EXISTS ix_pc_activity_category_rules_project_tag ON pc_activity_category_rules (project_tag);
CREATE UNIQUE INDEX IF NOT EXISTS ux_pc_activity_category_rules_rule_name ON pc_activity_category_rules (rule_name);
ALTER TABLE pc_activity_category_rules ALTER COLUMN created_at SET DEFAULT NOW();
ALTER TABLE pc_activity_category_rules ALTER COLUMN updated_at SET DEFAULT NOW();
CREATE TABLE IF NOT EXISTS pc_activity_classification_suggestions (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    cluster_key VARCHAR(256) NOT NULL,
    sample_count INT NOT NULL DEFAULT 0,
    total_duration_seconds DOUBLE PRECISION NOT NULL DEFAULT 0,
    sample_records_json JSONB NOT NULL DEFAULT '[]'::jsonb,
    sanitized_context_json JSONB NOT NULL DEFAULT '{{}}'::jsonb,
    current_category VARCHAR(64),
    suggested_category VARCHAR(64),
    suggested_project_tag VARCHAR(128),
    suggested_rules_json JSONB,
    user_feedback TEXT,
    llm_response_json JSONB,
    status VARCHAR(16) NOT NULL DEFAULT 'pending',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS ix_pc_activity_classification_suggestions_cluster_key ON pc_activity_classification_suggestions (cluster_key);
CREATE UNIQUE INDEX IF NOT EXISTS ux_pc_activity_classification_suggestions_pending_cluster ON pc_activity_classification_suggestions (cluster_key) WHERE status = 'pending';
CREATE INDEX IF NOT EXISTS ix_pc_activity_classification_suggestions_status ON pc_activity_classification_suggestions (status);
CREATE INDEX IF NOT EXISTS ix_pc_activity_classification_suggestions_updated_at ON pc_activity_classification_suggestions (updated_at);
CREATE TABLE IF NOT EXISTS pc_activity_classifications (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    record_key VARCHAR(256) NOT NULL,
    record_type VARCHAR(32) NOT NULL,
    device_id VARCHAR(128) NOT NULL,
    source_event_ids JSONB NOT NULL DEFAULT '[]'::jsonb,
    record_key_version VARCHAR(32) NOT NULL DEFAULT 'pc-fallback-v1',
    record_key_stability VARCHAR(16) NOT NULL DEFAULT 'low',
    source_type VARCHAR(32) NOT NULL DEFAULT 'fallback',
    source_bucket_ids JSONB NOT NULL DEFAULT '[]'::jsonb,
    interpretation_version VARCHAR(32) NOT NULL DEFAULT 'interpreted-aw-v1',
    started_at TIMESTAMPTZ NOT NULL,
    ended_at TIMESTAMPTZ NOT NULL,
    category_name VARCHAR(64) NOT NULL DEFAULT '其他',
    category_color VARCHAR(7) NOT NULL DEFAULT '#64748b',
    project_tag VARCHAR(128),
    confidence DOUBLE PRECISION NOT NULL DEFAULT 0.2,
    source VARCHAR(32) NOT NULL DEFAULT 'fallback',
    source_rule_id UUID,
    explanation TEXT NOT NULL DEFAULT '没有匹配到规则或启发式分类。',
    classifier_version VARCHAR(32) NOT NULL DEFAULT 'local-v1',
    classified_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    audit_id UUID
);
CREATE UNIQUE INDEX IF NOT EXISTS ux_pc_activity_classifications_record_key
    ON pc_activity_classifications (record_key);
CREATE INDEX IF NOT EXISTS ix_pc_activity_classifications_started_at
    ON pc_activity_classifications (started_at);
CREATE INDEX IF NOT EXISTS ix_pc_activity_classifications_device_id
    ON pc_activity_classifications (device_id);
CREATE INDEX IF NOT EXISTS ix_pc_activity_classifications_category_name
    ON pc_activity_classifications (category_name);
CREATE INDEX IF NOT EXISTS ix_pc_activity_classifications_project_tag
    ON pc_activity_classifications (project_tag);
CREATE INDEX IF NOT EXISTS ix_pc_activity_classifications_source_rule_id
    ON pc_activity_classifications (source_rule_id);
ALTER TABLE pc_activity_classifications ADD COLUMN IF NOT EXISTS record_key_version VARCHAR(32) NOT NULL DEFAULT 'pc-fallback-v1';
ALTER TABLE pc_activity_classifications ADD COLUMN IF NOT EXISTS record_key_stability VARCHAR(16) NOT NULL DEFAULT 'low';
ALTER TABLE pc_activity_classifications ADD COLUMN IF NOT EXISTS source_type VARCHAR(32) NOT NULL DEFAULT 'fallback';
ALTER TABLE pc_activity_classifications ADD COLUMN IF NOT EXISTS source_bucket_ids JSONB NOT NULL DEFAULT '[]'::jsonb;
ALTER TABLE pc_activity_classifications ADD COLUMN IF NOT EXISTS interpretation_version VARCHAR(32) NOT NULL DEFAULT 'interpreted-aw-v1';
CREATE INDEX IF NOT EXISTS ix_pc_activity_classifications_record_key_version
    ON pc_activity_classifications (record_key_version);
CREATE INDEX IF NOT EXISTS ix_pc_activity_classifications_source_type
    ON pc_activity_classifications (source_type);

CREATE TABLE IF NOT EXISTS pc_activity_classification_audits (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    operation VARCHAR(64) NOT NULL,
    rule_id UUID,
    suggestion_id UUID,
    range_mode VARCHAR(16) NOT NULL,
    date_from VARCHAR(16),
    date_to VARCHAR(16),
    affected_record_count INT NOT NULL DEFAULT 0,
    affected_duration_seconds DOUBLE PRECISION NOT NULL DEFAULT 0,
    affected_record_keys JSONB NOT NULL DEFAULT '[]'::jsonb,
    created_by_user_id UUID,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS ix_pc_activity_classification_audits_rule_id
    ON pc_activity_classification_audits (rule_id);
CREATE INDEX IF NOT EXISTS ix_pc_activity_classification_audits_suggestion_id
    ON pc_activity_classification_audits (suggestion_id);
CREATE INDEX IF NOT EXISTS ix_pc_activity_classification_audits_created_at
    ON pc_activity_classification_audits (created_at);

CREATE TABLE IF NOT EXISTS pc_activity_classification_settings (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    settings_key VARCHAR(64) NOT NULL DEFAULT 'default',
    recommended_minimum_classification_duration_minutes INT NOT NULL DEFAULT 5,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE UNIQUE INDEX IF NOT EXISTS ux_pc_activity_classification_settings_key
    ON pc_activity_classification_settings (settings_key);
INSERT INTO pc_activity_classification_settings (
    settings_key,
    recommended_minimum_classification_duration_minutes
)
VALUES ('default', 5)
ON CONFLICT (settings_key) DO NOTHING;

-- App knowledge base table
CREATE TABLE IF NOT EXISTS pc_app_signatures (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    process_name VARCHAR(256) NOT NULL,
    display_name VARCHAR(256) NOT NULL,
    category_path VARCHAR(256),
    productivity VARCHAR(32) DEFAULT 'neutral',
    description TEXT,
    source VARCHAR(32) NOT NULL DEFAULT 'builtin',
    confidence DOUBLE PRECISION NOT NULL DEFAULT 1.0,
    icon VARCHAR(16),
    search_keywords VARCHAR(512),
    last_seen_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE UNIQUE INDEX IF NOT EXISTS ux_pc_app_signatures_process_name ON pc_app_signatures (process_name);
CREATE INDEX IF NOT EXISTS ix_pc_app_signatures_display_name ON pc_app_signatures (display_name);

CREATE TABLE IF NOT EXISTS pc_app_knowledge_contexts (
    id uuid PRIMARY KEY,
    app_signature_id uuid NULL REFERENCES pc_app_signatures(id) ON DELETE SET NULL,
    process_name varchar(256) NOT NULL,
    pattern_type varchar(64) NOT NULL,
    pattern_value varchar(512) NOT NULL,
    target_category_name varchar(256) NULL,
    project_tag varchar(256) NULL,
    scope_summary varchar(512) NOT NULL,
    source varchar(64) NOT NULL,
    confidence double precision NOT NULL,
    enabled boolean NOT NULL,
    affected_record_count integer NOT NULL DEFAULT 0,
    affected_duration_seconds double precision NOT NULL DEFAULT 0,
    last_matched_at timestamptz NULL,
    source_rule_id uuid NULL,
    source_suggestion_id uuid NULL,
    created_at timestamptz NOT NULL,
    updated_at timestamptz NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS ix_pc_app_knowledge_contexts_app_pattern
    ON pc_app_knowledge_contexts(process_name, pattern_type, pattern_value);
CREATE INDEX IF NOT EXISTS ix_pc_app_knowledge_contexts_app_signature_id
    ON pc_app_knowledge_contexts(app_signature_id);
CREATE INDEX IF NOT EXISTS ix_pc_app_knowledge_contexts_category
    ON pc_app_knowledge_contexts(target_category_name);
CREATE INDEX IF NOT EXISTS ix_pc_app_knowledge_contexts_source_suggestion
    ON pc_app_knowledge_contexts(source_suggestion_id);

-- Seed app signatures (200+ common applications)
INSERT INTO pc_app_signatures (process_name, display_name, category_path, productivity, description, source, icon, confidence) VALUES
-- Development / Programming
('Code.exe', 'VS Code', '编程/折腾', 'productive', '轻量级代码编辑器', 'builtin', '💻', 0.99),
('code-insiders.exe', 'VS Code Insiders', '编程/折腾', 'productive', 'VS Code 预览版', 'builtin', '💻', 0.99),
('devenv.exe', 'Visual Studio', '编程/折腾', 'productive', '微软集成开发环境', 'builtin', '💻', 0.99),
('rider64.exe', 'JetBrains Rider', '编程/折腾', 'productive', '.NET 跨平台 IDE', 'builtin', '💻', 0.99),
('idea64.exe', 'IntelliJ IDEA', '编程/折腾', 'productive', 'Java 集成开发环境', 'builtin', '💻', 0.99),
('pycharm64.exe', 'PyCharm', '编程/折腾', 'productive', 'Python IDE', 'builtin', '💻', 0.99),
('webstorm64.exe', 'WebStorm', '编程/折腾', 'productive', '前端开发 IDE', 'builtin', '💻', 0.99),
('goland64.exe', 'GoLand', '编程/折腾', 'productive', 'Go 语言 IDE', 'builtin', '💻', 0.99),
('clion64.exe', 'CLion', '编程/折腾', 'productive', 'C/C++ IDE', 'builtin', '💻', 0.99),
('cursor.exe', 'Cursor', '编程/折腾', 'productive', 'AI 优先的代码编辑器', 'builtin', '🤖', 0.99),
('zed.exe', 'Zed', '编程/折腾', 'productive', '高性能代码编辑器', 'builtin', '💻', 0.99),
('sublime_text.exe', 'Sublime Text', '编程/折腾', 'productive', '轻量级文本编辑器', 'builtin', '📝', 0.99),
('notepad++.exe', 'Notepad++', '编程/折腾', 'productive', '文本编辑器', 'builtin', '📝', 0.99),
('Vim.exe', 'Vim', '编程/折腾', 'productive', '经典文本编辑器', 'builtin', '📝', 0.99),
('nvim-qt.exe', 'Neovim', '编程/折腾', 'productive', '现代 Vim 分支', 'builtin', '📝', 0.99),
('git-bash.exe', 'Git Bash', '编程/折腾', 'productive', 'Git 命令行', 'builtin', '🐙', 0.99),
-- JetBrains Tools (lowercase variants)
('rider.exe', 'JetBrains Rider', '编程/折腾', 'productive', NULL, 'builtin', '💻', 0.95),
('idea.exe', 'IntelliJ IDEA', '编程/折腾', 'productive', NULL, 'builtin', '💻', 0.95),
('pycharm.exe', 'PyCharm', '编程/折腾', 'productive', NULL, 'builtin', '💻', 0.95),
-- Terminal / Shell
('WindowsTerminal.exe', 'Windows Terminal', '编程/折腾', 'productive', 'Windows 终端', 'builtin', '🖥️', 0.99),
('wt.exe', 'Windows Terminal', '编程/折腾', 'productive', 'Windows 终端', 'builtin', '🖥️', 0.99),
('powershell.exe', 'PowerShell', '编程/折腾', 'productive', '微软命令行 Shell', 'builtin', '🖥️', 0.99),
('pwsh.exe', 'PowerShell Core', '编程/折腾', 'productive', '跨平台 PowerShell', 'builtin', '🖥️', 0.99),
('cmd.exe', '命令提示符', '编程/折腾', 'productive', 'Windows 命令行', 'builtin', '🖥️', 0.99),
('mintty.exe', 'Mintty', '编程/折腾', 'productive', 'Cygwin 终端', 'builtin', '🖥️', 0.99),
('alacritty.exe', 'Alacritty', '编程/折腾', 'productive', 'GPU 加速终端', 'builtin', '🖥️', 0.99),
('wezterm.exe', 'WezTerm', '编程/折腾', 'productive', '跨平台终端模拟器', 'builtin', '🖥️', 0.99),
('floaterm.exe', 'Floaterm', '编程/折腾', 'productive', '浮动终端', 'builtin', '🖥️', 0.99),
('MobaXterm*.exe', 'MobaXterm', '编程/折腾', 'productive', '增强型终端/远程桌面/SSH 客户端', 'builtin', '🖥️', 0.99),
('MobaXterm*', 'MobaXterm SSH客户端', '编程/折腾', 'productive', NULL, 'builtin', '🖥️', 0.95),
('putty.exe', 'PuTTY', '编程/折腾', 'productive', 'SSH/Telnet 客户端', 'builtin', '🔌', 0.99),
('winscp.exe', 'WinSCP', '编程/折腾', 'productive', 'SFTP/FTP 客户端', 'builtin', '📁', 0.99),
('FileZilla.exe', 'FileZilla', '编程/折腾', 'productive', 'FTP 客户端', 'builtin', '📁', 0.99),
-- Docker / DevOps
('docker.exe', 'Docker', '编程/折腾', 'productive', '容器化平台', 'builtin', '🐳', 0.99),
('docker-desktop.exe', 'Docker Desktop', '编程/折腾', 'productive', 'Docker 桌面版', 'builtin', '🐳', 0.99),
('kubectl.exe', 'kubectl', '编程/折腾', 'productive', 'Kubernetes 命令行工具', 'builtin', '☸️', 0.99),
('helm.exe', 'Helm', '编程/折腾', 'productive', 'Kubernetes 包管理器', 'builtin', '☸️', 0.99),
-- Database Tools
('pgadmin4.exe', 'pgAdmin', '编程/折腾', 'productive', 'PostgreSQL 管理工具', 'builtin', '🐘', 0.99),
('dbeaver.exe', 'DBeaver', '编程/折腾', 'productive', '通用数据库管理工具', 'builtin', '🗄️', 0.99),
('datagrip64.exe', 'DataGrip', '编程/折腾', 'productive', 'JetBrains 数据库 IDE', 'builtin', '🗄️', 0.99),
('AzureDataStudio.exe', 'Azure Data Studio', '编程/折腾', 'productive', '数据管理工具', 'builtin', '🗄️', 0.99),
('mysql-workbench.exe', 'MySQL Workbench', '编程/折腾', 'productive', 'MySQL 管理工具', 'builtin', '🗄️', 0.99),
('redis-server.exe', 'Redis', '编程/折腾', 'productive', '内存数据库', 'builtin', '⚡', 0.99),
-- Browser
('chrome.exe', 'Chrome', NULL, NULL, 'Google Chrome 浏览器', 'builtin', '🌐', 0.99),
('msedge.exe', 'Edge', NULL, NULL, 'Microsoft Edge 浏览器', 'builtin', '🌐', 0.99),
('firefox.exe', 'Firefox', NULL, NULL, 'Mozilla Firefox 浏览器', 'builtin', '🦊', 0.99),
('brave.exe', 'Brave', NULL, NULL, 'Brave 浏览器', 'builtin', '🦁', 0.99),
('opera.exe', 'Opera', NULL, NULL, 'Opera 浏览器', 'builtin', '🌐', 0.99),
('vivaldi.exe', 'Vivaldi', NULL, NULL, 'Vivaldi 浏览器', 'builtin', '🌐', 0.99),
('Safari.exe', 'Safari', '文档', 'neutral', 'Apple Safari 浏览器', 'builtin', '🌐', 0.99),
-- Office / Productivity
('WINWORD.EXE', 'Word', '文档', 'productive', '微软文字处理软件', 'builtin', '📄', 0.99),
('EXCEL.EXE', 'Excel', '文档', 'productive', '微软电子表格软件', 'builtin', '📊', 0.99),
('POWERPNT.EXE', 'PowerPoint', '文档', 'productive', '微软演示文稿软件', 'builtin', '📽️', 0.99),
('OUTLOOK.EXE', 'Outlook', '聊天', 'productive', '微软邮件/日历客户端', 'builtin', '📧', 0.99),
('ONENOTE.EXE', 'OneNote', '文档', 'productive', '微软数字笔记本', 'builtin', '📓', 0.99),
('Teams.exe', 'Microsoft Teams', '聊天', 'productive', '团队协作平台', 'builtin', '💬', 0.99),
('ms-teams.exe', 'Microsoft Teams', '聊天', 'productive', NULL, 'builtin', '💬', 0.95),
('notion.exe', 'Notion', '文档', 'productive', '笔记/知识库/项目管理', 'builtin', '📝', 0.99),
('obsidian.exe', 'Obsidian', '文档', 'productive', '本地优先的知识管理工具', 'builtin', '🗒️', 0.99),
('typora.exe', 'Typora', '文档', 'productive', '极简 Markdown 编辑器', 'builtin', '📝', 0.99),
('marktext.exe', 'MarkText', '文档', 'productive', 'Markdown 编辑器', 'builtin', '📝', 0.99),
('Logseq.exe', 'Logseq', '文档', 'productive', '开源知识管理工具', 'builtin', '📓', 0.99),
('Acrobat.exe', 'Adobe Acrobat', '文档', 'neutral', 'PDF 阅读/编辑', 'builtin', '📕', 0.99),
('AcroRd32.exe', 'Adobe Reader', '文档', 'neutral', 'PDF 阅读器', 'builtin', '📕', 0.99),
('FoxitPDFReader.exe', 'Foxit Reader', '文档', 'neutral', 'PDF 阅读器', 'builtin', '📕', 0.99),
('wps.exe', 'WPS Office', '文档', 'productive', '办公套件', 'builtin', '📄', 0.99),
('wpsoffice.exe', 'WPS Office', '文档', 'productive', NULL, 'builtin', '📄', 0.95),
-- Communication
('WeChat.exe', '微信', '聊天', 'neutral', '即时通讯/社交平台', 'builtin', '💬', 0.99),
('WeChatAppEx.exe', '微信', '聊天', 'neutral', NULL, 'builtin', '💬', 0.99),
('WeChatStore.exe', '微信', '聊天', 'neutral', NULL, 'builtin', '💬', 0.99),
('QQ.exe', 'QQ', '聊天', 'neutral', '即时通讯软件', 'builtin', '💬', 0.99),
('QQBrowser.exe', 'QQ 浏览器', '文档', 'neutral', '腾讯浏览器', 'builtin', '🌐', 0.99),
('TIM.exe', 'TIM', '聊天', 'productive', '腾讯办公版 QQ', 'builtin', '💬', 0.99),
('DingTalk.exe', '钉钉', '聊天', 'productive', '阿里企业通讯/协作平台', 'builtin', '📌', 0.99),
('DingTalkLauncher.exe', '钉钉', '聊天', 'productive', NULL, 'builtin', '📌', 0.99),
('WeMeeting.exe', '腾讯会议', '聊天', 'productive', '腾讯视频会议', 'builtin', '📹', 0.99),
('wemeetapp.exe', '腾讯会议', '聊天', 'productive', NULL, 'builtin', '📹', 0.99),
('Slack.exe', 'Slack', '聊天', 'productive', '团队协作平台', 'builtin', '💬', 0.99),
('Discord.exe', 'Discord', '聊天', 'neutral', '游戏/社区即时通讯', 'builtin', '🎧', 0.99),
('Telegram.exe', 'Telegram', '聊天', 'neutral', '加密即时通讯', 'builtin', '✈️', 0.99),
('zoom.exe', 'Zoom', '聊天', 'productive', '视频会议平台', 'builtin', '📹', 0.99),
('thunderbird.exe', 'Thunderbird', '聊天', 'productive', '开源邮件客户端', 'builtin', '📧', 0.99),
-- Games
('isaac-ng.exe', '以撒的结合', '游戏', 'distracting', 'Roguelike 地牢射击游戏', 'builtin', '🎮', 0.99),
('isaac-ng-steam.exe', '以撒的结合', '游戏', 'distracting', NULL, 'builtin', '🎮', 0.95),
('VALORANT-Win64-Shipping.exe', '无畏契约', '游戏', 'distracting', '5v5 战术射击游戏', 'builtin', '🎮', 0.99),
('RiotClientServices.exe', 'Riot 客户端', '游戏', 'distracting', 'Riot 游戏启动器', 'builtin', '🎮', 0.99),
('LeagueClient.exe', '英雄联盟', '游戏', 'distracting', 'MOBA 游戏客户端', 'builtin', '🎮', 0.99),
('LeagueClientUx.exe', '英雄联盟', '游戏', 'distracting', '英雄联盟 UI 进程', 'builtin', '🎮', 0.99),
('StarRail.exe', '崩坏：星穹铁道', '游戏', 'distracting', '米哈游 RPG 游戏', 'builtin', '🎮', 0.99),
('GenshinImpact.exe', '原神', '游戏', 'distracting', '米哈游开放世界 RPG', 'builtin', '🎮', 0.99),
('YuanShen.exe', '原神', '游戏', 'distracting', '原神国服版本', 'builtin', '🎮', 0.99),
('Steam.exe', 'Steam', '游戏', 'distracting', '游戏发行平台', 'builtin', '🎮', 0.99),
('steamwebhelper.exe', 'Steam', '游戏', 'distracting', 'Steam 辅助进程', 'builtin', '🎮', 0.85),
('EpicGamesLauncher.exe', 'Epic 游戏启动器', '游戏', 'distracting', 'Epic 游戏平台', 'builtin', '🎮', 0.99),
('Minecraft.exe', 'Minecraft', '游戏', 'distracting', '沙盒建造游戏', 'builtin', '⛏️', 0.99),
('MinecraftLauncher.exe', 'Minecraft 启动器', '游戏', 'distracting', '我的世界启动器', 'builtin', '⛏️', 0.99),
('javaw.exe', 'Java (游戏)', '游戏', 'neutral', 'Java 运行时（游戏相关）', 'builtin', '☕', 0.50),
('StardewValley.exe', '星露谷物语', '游戏', 'distracting', '农场经营模拟 RPG', 'builtin', '🌾', 0.99),
('StardewModdingAPI.exe', '星露谷物语 (SMAPI)', '游戏', 'distracting', '星露谷物语 Mod 加载器', 'builtin', '🌾', 0.99),
('HollowKnight.exe', '空洞骑士', '游戏', 'distracting', '类银河城动作游戏', 'builtin', '🎮', 0.99),
('Celeste.exe', '蔚蓝', '游戏', 'distracting', '平台跳跃游戏', 'builtin', '🎮', 0.99),
('Terraria.exe', '泰拉瑞亚', '游戏', 'distracting', '沙盒冒险游戏', 'builtin', '🎮', 0.99),
('tModLoader.exe', 'tModLoader', '游戏', 'distracting', '泰拉瑞亚 Mod 加载器', 'builtin', '🎮', 0.99),
('factorio.exe', '异星工厂', '游戏', 'distracting', '工厂自动化模拟游戏', 'builtin', '🏭', 0.99),
('LethalCompany.exe', '致命公司', '游戏', 'distracting', '恐怖合作游戏', 'builtin', '🎮', 0.99),
-- Media / Entertainment
('Spotify.exe', 'Spotify', '其他', 'neutral', '音乐流媒体平台', 'builtin', '🎵', 0.99),
('vlc.exe', 'VLC 播放器', '视频', 'neutral', '开源多媒体播放器', 'builtin', '🎬', 0.99),
('PotPlayer.exe', 'PotPlayer', '视频', 'neutral', '多功能视频播放器', 'builtin', '🎬', 0.99),
('PotPlayerMini64.exe', 'PotPlayer', '视频', 'neutral', NULL, 'builtin', '🎬', 0.99),
('wmplayer.exe', 'Windows Media Player', '视频', 'neutral', '微软媒体播放器', 'builtin', '🎬', 0.99),
('mpv.exe', 'mpv', '视频', 'neutral', '轻量级视频播放器', 'builtin', '🎬', 0.99),
('bilibili.exe', '哔哩哔哩', '视频', 'distracting', 'B站 桌面客户端', 'builtin', '📺', 0.99),
('Netflix.exe', 'Netflix', '视频', 'distracting', '流媒体视频平台', 'builtin', '📺', 0.99),
('YouTube Music.exe', 'YouTube Music', '其他', 'neutral', '谷歌音乐流媒体', 'builtin', '🎵', 0.99),
-- File Management
('explorer.exe', '资源管理器', '文档', 'neutral', 'Windows 文件管理器', 'builtin', '📁', 0.99),
('Everything.exe', 'Everything', '文档', 'productive', '超快文件搜索工具', 'builtin', '🔍', 0.99),
('TotalCmd.exe', 'Total Commander', '文档', 'productive', '文件管理器', 'builtin', '📁', 0.99),
('TotalCommander.exe', 'Total Commander', '文档', 'productive', NULL, 'builtin', '📁', 0.99),
('DoubleCMD.exe', 'Double Commander', '文档', 'productive', '双面板文件管理器', 'builtin', '📁', 0.99),
('7zFM.exe', '7-Zip', '文档', 'neutral', '压缩文件管理器', 'builtin', '🗜️', 0.99),
('WinRAR.exe', 'WinRAR', '文档', 'neutral', '压缩文件管理器', 'builtin', '🗜️', 0.99),
('Bandizip.exe', 'Bandizip', '文档', 'neutral', '压缩文件管理器', 'builtin', '🗜️', 0.99),
-- Design / Creative
('Photoshop.exe', 'Photoshop', '编程/折腾', 'productive', 'Adobe 图像编辑软件', 'builtin', '🎨', 0.99),
('Adobe Premiere Pro.exe', 'Premiere Pro', '编程/折腾', 'productive', 'Adobe 视频剪辑软件', 'builtin', '🎬', 0.99),
('Adobe Illustrator.exe', 'Illustrator', '编程/折腾', 'productive', 'Adobe 矢量图形编辑器', 'builtin', '🎨', 0.99),
('Figma.exe', 'Figma', '编程/折腾', 'productive', 'UI/UX 设计协作工具', 'builtin', '🎨', 0.99),
('blender.exe', 'Blender', '编程/折腾', 'productive', '3D 创作套件', 'builtin', '🎨', 0.99),
('aseprite.exe', 'Aseprite', '编程/折腾', 'productive', '像素画工具', 'builtin', '🎨', 0.99),
-- System / Utilities
('Taskmgr.exe', '任务管理器', '编程/折腾', 'neutral', 'Windows 任务管理器', 'builtin', '⚙️', 0.99),
('regedit.exe', '注册表编辑器', '编程/折腾', 'neutral', 'Windows 注册表编辑器', 'builtin', '⚙️', 0.99),
('msconfig.exe', '系统配置', '编程/折腾', 'neutral', 'Windows 系统配置工具', 'builtin', '⚙️', 0.99),
('gpedit.msc', '本地组策略编辑器', '编程/折腾', 'neutral', 'Windows 组策略管理', 'builtin', '⚙️', 0.99),
('services.msc', '服务管理器', '编程/折腾', 'neutral', 'Windows 服务管理', 'builtin', '⚙️', 0.99),
('compmgmt.msc', '计算机管理', '编程/折腾', 'neutral', 'Windows 计算机管理', 'builtin', '⚙️', 0.99),
('diskmgmt.msc', '磁盘管理', '编程/折腾', 'neutral', 'Windows 磁盘管理', 'builtin', '💾', 0.99),
('perfmon.exe', '性能监视器', '编程/折腾', 'neutral', 'Windows 性能监控', 'builtin', '📊', 0.99),
('resmon.exe', '资源监视器', '编程/折腾', 'neutral', 'Windows 资源监视器', 'builtin', '📊', 0.99),
('procmon.exe', 'Process Monitor', '编程/折腾', 'productive', '进程监控工具', 'builtin', '🔍', 0.99),
('procexp.exe', 'Process Explorer', '编程/折腾', 'productive', '增强型任务管理器', 'builtin', '🔍', 0.99),
('procexp64.exe', 'Process Explorer', '编程/折腾', 'productive', NULL, 'builtin', '🔍', 0.99),
('ShareX.exe', 'ShareX', '文档', 'neutral', '截屏/录屏工具', 'builtin', '📸', 0.99),
('Snipaste.exe', 'Snipaste', '文档', 'productive', '截图/贴图工具', 'builtin', '📸', 0.99),
('PowerToys.exe', 'Microsoft PowerToys', '编程/折腾', 'productive', 'Windows 效率工具集', 'builtin', '🔧', 0.99),
('powertoys.exe', 'Microsoft PowerToys', '编程/折腾', 'productive', NULL, 'builtin', '🔧', 0.95),
('AutoHotkey*.exe', 'AutoHotkey', '编程/折腾', 'productive', '自动化脚本工具', 'builtin', '⚡', 0.99),
('autohotkey.exe', 'AutoHotkey', '编程/折腾', 'productive', NULL, 'builtin', '⚡', 0.99),
-- Remote Access
('mstsc.exe', '远程桌面连接', '编程/折腾', 'productive', 'Windows 远程桌面', 'builtin', '🖥️', 0.99),
('AnyDesk.exe', 'AnyDesk', '编程/折腾', 'neutral', '远程桌面软件', 'builtin', '🖥️', 0.99),
('TeamViewer.exe', 'TeamViewer', '编程/折腾', 'neutral', '远程控制软件', 'builtin', '🖥️', 0.99),
('SunloginClient.exe', '向日葵', '编程/折腾', 'neutral', '国产远程控制软件', 'builtin', '🖥️', 0.99),
-- Cloud Sync
('OneDrive.exe', 'OneDrive', '文档', 'neutral', '微软云盘同步客户端', 'builtin', '☁️', 0.99),
('Dropbox.exe', 'Dropbox', '文档', 'neutral', '云存储同步', 'builtin', '☁️', 0.99),
('百度云.exe', '百度网盘', '其他', 'neutral', '百度网盘客户端', 'builtin', '☁️', 0.99),
('BaiduNetdisk.exe', '百度网盘', '其他', 'neutral', NULL, 'builtin', '☁️', 0.99),
('aliyunpan.exe', '阿里云盘', '文档', 'neutral', '阿里云盘客户端', 'builtin', '☁️', 0.99),
-- Security
('egui.exe', 'ESET', '编程/折腾', 'neutral', 'ESET 安全软件', 'builtin', '🛡️', 0.99),
('avguix.exe', 'Avast', '编程/折腾', 'neutral', 'Avast 杀毒软件', 'builtin', '🛡️', 0.99),
('MsMpEng.exe', 'Microsoft Defender', '编程/折腾', 'neutral', 'Windows 安全中心', 'builtin', '🛡️', 0.99),
-- AI / LLM
('ollama.exe', 'Ollama', '编程/折腾', 'productive', '本地大语言模型运行工具', 'builtin', '🤖', 0.99),
('ollama-app.exe', 'Ollama', '编程/折腾', 'productive', NULL, 'builtin', '🤖', 0.99),
('lm-studio.exe', 'LM Studio', '编程/折腾', 'productive', '本地模型运行/测试工具', 'builtin', '🤖', 0.99),
('ChatGPT.exe', 'ChatGPT', '编程/折腾', 'productive', 'OpenAI 聊天客户端', 'builtin', '🤖', 0.99),
-- Note taking special
('Notion.exe', 'Notion', '文档', 'productive', '笔记/知识库/项目管理', 'builtin', '📝', 0.99),
-- Misc / Uncategorized
('calc.exe', '计算器', '文档', 'neutral', 'Windows 计算器', 'builtin', '🧮', 0.99),
('notepad.exe', '记事本', '文档', 'neutral', 'Windows 记事本', 'builtin', '📝', 0.99),
('write.exe', '写字板', '文档', 'neutral', 'Windows 写字板', 'builtin', '📝', 0.99),
('mspaint.exe', '画图', '编程/折腾', 'neutral', 'Windows 画图工具', 'builtin', '🎨', 0.99),
('snippingtool.exe', '截图工具', '文档', 'neutral', 'Windows 截图工具', 'builtin', '📸', 0.99),
('magnify.exe', '放大镜', '文档', 'neutral', 'Windows 放大镜工具', 'builtin', '🔍', 0.99),
('osk.exe', '屏幕键盘', '文档', 'neutral', 'Windows 屏幕键盘', 'builtin', '⌨️', 0.99),
('stikynot.exe', '便签', '文档', 'neutral', 'Windows 便签', 'builtin', '📌', 0.99)
ON CONFLICT (process_name) DO NOTHING;

-- Builtin activity category rules (unified 7-category names; browser rule removed per §0.3)
INSERT INTO pc_activity_category_rules (rule_name, scope, category_name, project_tag, color, priority, source, status, conditions_json, confidence, explanation) VALUES
('Builtin: VS Code', 'activity', '编程/折腾', NULL, '#6B5EE4', 300, 'builtin', 'active', '{{"all":[{{"field":"appNameNormalized","op":"equals","value":"code"}}]}}'::jsonb, 0.9, 'Builtin app rule.'),
('Builtin: Rider', 'activity', '编程/折腾', NULL, '#6B5EE4', 300, 'builtin', 'active', '{{"all":[{{"field":"appNameNormalized","op":"equals","value":"rider"}}]}}'::jsonb, 0.9, 'Builtin app rule.'),
('Builtin: Terminal', 'activity', '编程/折腾', NULL, '#6B5EE4', 300, 'builtin', 'active', '{{"all":[{{"field":"appNameNormalized","op":"containsAny","value":["windowsterminal","terminal","powershell","cmd"]}}]}}'::jsonb, 0.85, 'Builtin terminal rule.'),
('Builtin: Chat apps', 'activity', '聊天', NULL, '#3B82F6', 300, 'builtin', 'active', '{{"all":[{{"field":"appNameNormalized","op":"containsAny","value":["wechat","dingtalk","qq","telegram","slack","discord","teams"]}}]}}'::jsonb, 0.85, 'Builtin communication rule.'),
('Builtin: Office apps', 'activity', '文档', NULL, '#F59E0B', 300, 'builtin', 'active', '{{"all":[{{"field":"appNameNormalized","op":"containsAny","value":["winword","excel","powerpnt","notion","obsidian","typora"]}}]}}'::jsonb, 0.85, 'Builtin office rule.'),
('Builtin: File managers', 'activity', '文档', NULL, '#F59E0B', 300, 'builtin', 'active', '{{"all":[{{"field":"appNameNormalized","op":"containsAny","value":["explorer","everything","totalcommander"]}}]}}'::jsonb, 0.85, 'Builtin file rule.')
ON CONFLICT DO NOTHING;
INSERT INTO pc_activity_category_rules (rule_name, scope, category_name, project_tag, color, priority, source, status, conditions_json, confidence, explanation)
SELECT
    'Migrated app rule: ' || app_pattern,
    'activity',
    category_name,
    NULL,
    color,
    priority + 1000,
    CASE WHEN is_builtin THEN 'builtin' ELSE 'user' END,
    'active',
    jsonb_build_object('all', jsonb_build_array(jsonb_build_object('field', 'appNameNormalized', 'op', 'equals', 'value', lower(regexp_replace(app_pattern, '\.exe$', '', 'i'))))),
    0.95,
    'Migrated from pc_app_categories.'
FROM pc_app_categories
WHERE NOT EXISTS (
    SELECT 1
    FROM pc_activity_category_rules r
    WHERE r.rule_name = 'Migrated app rule: ' || pc_app_categories.app_pattern
);

-- Phase 2: pc_categories (hierarchical classification tree)
CREATE TABLE IF NOT EXISTS pc_categories (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    parent_id UUID REFERENCES pc_categories(id) ON DELETE RESTRICT,
    name VARCHAR(64) NOT NULL,
    color VARCHAR(7) NOT NULL DEFAULT '#64748b',
    icon VARCHAR(32),
    productivity VARCHAR(16) NOT NULL DEFAULT 'neutral',
    sort_order INT NOT NULL DEFAULT 0,
    is_builtin BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS ix_pc_categories_parent_id ON pc_categories (parent_id);
CREATE INDEX IF NOT EXISTS ix_pc_categories_name ON pc_categories (name);
CREATE INDEX IF NOT EXISTS ix_pc_categories_sort_order ON pc_categories (sort_order);

-- Native Tracker: pc_tracker_events
CREATE TABLE IF NOT EXISTS pc_tracker_events (
    id BIGSERIAL PRIMARY KEY,
    device_id VARCHAR(64) NOT NULL,
    timestamp TIMESTAMPTZ NOT NULL,
    duration DOUBLE PRECISION NOT NULL DEFAULT 0,
    event_type VARCHAR(16) NOT NULL,
    exe_path TEXT,
    app_name VARCHAR(256),
    display_name VARCHAR(256),
    window_title TEXT,
    command_line TEXT,
    is_idle BOOLEAN DEFAULT FALSE,
    is_media_active BOOLEAN DEFAULT FALSE,
    url TEXT,
    domain VARCHAR(512),
    page_path TEXT,
    audible BOOLEAN,
    incognito BOOLEAN,
    tab_count INTEGER,
    page_visit_count INTEGER DEFAULT 0,
    page_visit_duration DOUBLE PRECISION DEFAULT 0,
    browser VARCHAR(16),
    instance_id VARCHAR(128),
    raw_json JSONB,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    date DATE NOT NULL
);
ALTER TABLE pc_tracker_events ADD COLUMN IF NOT EXISTS browser VARCHAR(16);
ALTER TABLE pc_tracker_events ADD COLUMN IF NOT EXISTS instance_id VARCHAR(128);
CREATE INDEX IF NOT EXISTS idx_tracker_events_device_date ON pc_tracker_events(device_id, date);
CREATE INDEX IF NOT EXISTS idx_tracker_events_timestamp ON pc_tracker_events(timestamp);
CREATE INDEX IF NOT EXISTS idx_tracker_events_app ON pc_tracker_events(app_name, date);
CREATE INDEX IF NOT EXISTS idx_tracker_events_event_type ON pc_tracker_events(event_type);
CREATE INDEX IF NOT EXISTS idx_tracker_events_is_idle ON pc_tracker_events(is_idle);
CREATE INDEX IF NOT EXISTS idx_tracker_events_browser ON pc_tracker_events(browser);
CREATE INDEX IF NOT EXISTS idx_tracker_events_instance ON pc_tracker_events(instance_id);
CREATE UNIQUE INDEX IF NOT EXISTS ux_tracker_events_dedup ON pc_tracker_events(device_id, timestamp, duration, event_type, app_name);

-- Native Tracker: pc_tracker_health
CREATE TABLE IF NOT EXISTS pc_tracker_health (
    id BIGSERIAL PRIMARY KEY,
    device_id VARCHAR(64) NOT NULL,
    status VARCHAR(32) NOT NULL DEFAULT 'running',
    uptime_seconds DOUBLE PRECISION NOT NULL DEFAULT 0,
    hook_active BOOLEAN NOT NULL DEFAULT TRUE,
    poll_count BIGINT NOT NULL DEFAULT 0,
    sessions_created BIGINT NOT NULL DEFAULT 0,
    events_uploaded BIGINT NOT NULL DEFAULT 0,
    upload_failures BIGINT NOT NULL DEFAULT 0,
    last_error TEXT,
    browser_connected BOOLEAN NOT NULL DEFAULT FALSE,
    browser_heartbeat_age_seconds DOUBLE PRECISION,
    reported_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS ix_pc_tracker_health_device_id ON pc_tracker_health(device_id);
CREATE INDEX IF NOT EXISTS ix_pc_tracker_health_reported_at ON pc_tracker_health(reported_at);
CREATE INDEX IF NOT EXISTS ix_pc_tracker_health_device_reported ON pc_tracker_health(device_id, reported_at);
CREATE UNIQUE INDEX IF NOT EXISTS ux_pc_tracker_health_device ON pc_tracker_health(device_id);
""";

    private readonly PimDbContext _db;

    public PcTrackerSchemaInitializer(PimDbContext db)
    {
        _db = db;
    }

    public async Task InitializeAsync(CancellationToken ct = default)
    {
        await _db.Database.ExecuteSqlRawAsync(SchemaSql, ct);
    }
}
