// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Pim.Infrastructure.Data;

#nullable disable

namespace Pim.Infrastructure.Data.Migrations
{
    [DbContext(typeof(PimDbContext))]
    partial class PimDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Pim.Infrastructure.Data.Entities.LoginAttemptEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("AttemptedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("attempted_at");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("ip_address");

                    b.Property<bool>("Success")
                        .HasColumnType("boolean")
                        .HasColumnName("success");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("IpAddress", "AttemptedAt");

                    b.ToTable("login_attempts");
                });

            modelBuilder.Entity("Pim.Infrastructure.Data.Entities.RefreshTokenEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("token_hash");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash");

                    b.HasIndex("UserId");

                    b.ToTable("refresh_tokens");
                });

            modelBuilder.Entity("Pim.Infrastructure.Data.Entities.UserEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("role");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("users");
                });

            modelBuilder.Entity("Pim.Module.Calendar.Entities.CalendarEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)")
                        .HasColumnName("color");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean")
                        .HasColumnName("is_default");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("kind");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("calendars");
                });

            modelBuilder.Entity("Pim.Module.Calendar.Entities.EventEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CalendarId")
                        .HasColumnType("uuid")
                        .HasColumnName("calendar_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<DateTimeOffset>("DtEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dtend");

                    b.Property<DateTimeOffset>("DtStamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dtstamp");

                    b.Property<DateTimeOffset>("DtStart")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dtstart");

                    b.Property<string>("Location")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("location");

                    b.Property<string>("Organizer")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("organizer");

                    b.Property<string>("OutlookEventId")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("outlook_event_id");

                    b.Property<string>("RRule")
                        .HasColumnType("text")
                        .HasColumnName("rrule");

                    b.Property<Guid?>("SchedulePlanId")
                        .HasColumnType("uuid")
                        .HasColumnName("schedule_plan_id");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("source");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("title");

                    b.Property<string>("Uid")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("uid");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("CalendarId");

                    b.HasIndex("Uid");

                    b.ToTable("events");
                });

            modelBuilder.Entity("Pim.Module.Calendar.Entities.OutlookConnectionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<byte[]>("AccessTokenEncrypted")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("access_token_encrypted");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("LastSyncedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_synced_at");

                    b.Property<byte[]>("RefreshTokenEncrypted")
                        .HasColumnType("bytea")
                        .HasColumnName("refresh_token_encrypted");

                    b.Property<DateTimeOffset?>("SubscriptionExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("subscription_expires_at");

                    b.Property<string>("SubscriptionId")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("subscription_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("outlook_connections");
                });

            modelBuilder.Entity("Pim.Module.Calendar.Entities.PendingConfirmationEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("ConfirmedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("confirmed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("summary");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("type");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("Status");

                    b.HasIndex("UserId");

                    b.ToTable("pending_confirmations");
                });

            modelBuilder.Entity("Pim.Module.Calendar.Entities.SchedulingFeedbackEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Context")
                        .HasColumnType("jsonb")
                        .HasColumnName("context");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("PlanOptions")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("plan_options");

                    b.Property<int>("SelectedIndex")
                        .HasColumnType("integer")
                        .HasColumnName("selected_index");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("scheduling_feedback");
                });

            modelBuilder.Entity("Pim.Module.Calendar.Entities.TaskEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("CalendarId")
                        .HasColumnType("uuid")
                        .HasColumnName("calendar_id");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<DateTimeOffset?>("DtStart")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dtstart");

                    b.Property<DateTimeOffset?>("Due")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("due");

                    b.Property<TimeSpan?>("EstimatedDuration")
                        .HasColumnType("interval")
                        .HasColumnName("estimated_duration");

                    b.Property<bool>("IsInbox")
                        .HasColumnType("boolean")
                        .HasColumnName("is_inbox");

                    b.Property<TimeSpan?>("MinimumSegment")
                        .HasColumnType("interval")
                        .HasColumnName("minimum_segment");

                    b.Property<Guid?>("ParentTaskId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_task_id");

                    b.Property<int>("PercentComplete")
                        .HasColumnType("integer")
                        .HasColumnName("percent_complete");

                    b.Property<int>("Priority")
                        .HasColumnType("integer")
                        .HasColumnName("priority");

                    b.Property<Guid?>("SchedulePlanId")
                        .HasColumnType("uuid")
                        .HasColumnName("schedule_plan_id");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("title");

                    b.Property<string>("Uid")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("uid");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("CalendarId");

                    b.HasIndex("ParentTaskId");

                    b.HasIndex("Status");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId", "CalendarId");

                    b.ToTable("tasks");
                });

            modelBuilder.Entity("Pim.Module.PcTracker.Entities.ActivityCategoryRuleEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()")
                        .HasColumnName("id");

                    b.Property<string>("CategoryName")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("category_name");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)")
                        .HasColumnName("color");

                    b.Property<string>("ConditionsJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("conditions_json");

                    b.Property<double>("Confidence")
                        .HasColumnType("double precision")
                        .HasColumnName("confidence");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Explanation")
                        .HasColumnType("text")
                        .HasColumnName("explanation");

                    b.Property<int>("Priority")
                        .HasColumnType("integer")
                        .HasColumnName("priority");

                    b.Property<string>("ProjectTag")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("project_tag");

                    b.Property<string>("RuleName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("rule_name");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("scope");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("source");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("CategoryName")
                        .HasDatabaseName("ix_pc_activity_category_rules_category_name");

                    b.HasIndex("Priority")
                        .HasDatabaseName("ix_pc_activity_category_rules_priority");

                    b.HasIndex("ProjectTag")
                        .HasDatabaseName("ix_pc_activity_category_rules_project_tag");

                    b.HasIndex("RuleName")
                        .IsUnique()
                        .HasDatabaseName("ux_pc_activity_category_rules_rule_name");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_pc_activity_category_rules_status");

                    b.ToTable("pc_activity_category_rules", (string)null);
                });

            modelBuilder.Entity("Pim.Module.PcTracker.Entities.ActivityClassificationSuggestionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()")
                        .HasColumnName("id");

                    b.Property<string>("ClusterKey")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("cluster_key");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CurrentCategory")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("current_category");

                    b.Property<string>("LlmResponseJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("llm_response_json");

                    b.Property<int>("SampleCount")
                        .HasColumnType("integer")
                        .HasColumnName("sample_count");

                    b.Property<string>("SampleRecordsJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("sample_records_json");

                    b.Property<string>("SanitizedContextJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("sanitized_context_json");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<string>("SuggestedCategory")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("suggested_category");

                    b.Property<string>("SuggestedProjectTag")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("suggested_project_tag");

                    b.Property<string>("SuggestedRulesJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("suggested_rules_json");

                    b.Property<double>("TotalDurationSeconds")
                        .HasColumnType("double precision")
                        .HasColumnName("total_duration_seconds");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UserFeedback")
                        .HasColumnType("text")
                        .HasColumnName("user_feedback");

                    b.HasKey("Id");

                    b.HasIndex("ClusterKey")
                        .IsUnique()
                        .HasDatabaseName("ux_pc_activity_classification_suggestions_pending_cluster")
                        .HasFilter("status = 'pending'");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_pc_activity_classification_suggestions_status");

                    b.HasIndex("UpdatedAt")
                        .HasDatabaseName("ix_pc_activity_classification_suggestions_updated_at");

                    b.ToTable("pc_activity_classification_suggestions", (string)null);
                });

            modelBuilder.Entity("Pim.Module.PcTracker.Entities.AppCategoryEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()")
                        .HasColumnName("id");

                    b.Property<string>("AppPattern")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("app_pattern");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("category_name");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)")
                        .HasColumnName("color");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsBuiltin")
                        .HasColumnType("boolean")
                        .HasColumnName("is_builtin");

                    b.Property<int>("Priority")
                        .HasColumnType("integer")
                        .HasColumnName("priority");

                    b.HasKey("Id");

                    b.HasIndex("CategoryName");

                    b.HasIndex("Priority");

                    b.ToTable("pc_app_categories", (string)null);
                });

            modelBuilder.Entity("Pim.Module.PcTracker.Entities.AwBucketEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("AwDeviceId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("aw_device_id");

                    b.Property<string>("BucketId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("bucket_id");

                    b.Property<string>("BucketType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("type");

                    b.Property<string>("Client")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("client");

                    b.Property<DateTimeOffset?>("CreatedAtSource")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_source");

                    b.Property<string>("DataJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("data_json");

                    b.Property<string>("Hostname")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("hostname");

                    b.Property<DateTimeOffset?>("LastUpdatedSource")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_updated_source");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<string>("PimDeviceId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("pim_device_id");

                    b.Property<DateTimeOffset>("SeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("seen_at");

                    b.HasKey("Id");

                    b.HasIndex("BucketType")
                        .HasDatabaseName("ix_pc_aw_buckets_type");

                    b.HasIndex("SeenAt")
                        .HasDatabaseName("ix_pc_aw_buckets_seen_at");

                    b.HasIndex("PimDeviceId", "BucketId")
                        .IsUnique()
                        .HasDatabaseName("ux_pc_aw_buckets_device_bucket");

                    b.ToTable("pc_aw_buckets");
                });

            modelBuilder.Entity("Pim.Module.PcTracker.Entities.AwEventEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("AfkStatus")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("afk_status");

                    b.Property<string>("AppName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("app_name");

                    b.Property<string>("AppNameNormalized")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("app_name_normalized");

                    b.Property<string>("AwDeviceId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("aw_device_id");

                    b.Property<string>("AwHostname")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("aw_hostname");

                    b.Property<string>("BucketClient")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("bucket_client");

                    b.Property<string>("BucketId")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("bucket_id");

                    b.Property<string>("BucketType")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("bucket_type");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DataJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("data_json");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("device_id");

                    b.Property<double>("Duration")
                        .HasColumnType("double precision")
                        .HasColumnName("duration");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("event_type");

                    b.Property<long?>("SourceEventId")
                        .HasColumnType("bigint")
                        .HasColumnName("source_event_id");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("WindowTitle")
                        .HasColumnType("text")
                        .HasColumnName("window_title");

                    b.HasKey("Id");

                    b.HasIndex("AppNameNormalized")
                        .HasDatabaseName("ix_pc_aw_events_app_name_normalized");

                    b.HasIndex("BucketId")
                        .HasDatabaseName("ix_pc_aw_events_bucket_id");

                    b.HasIndex("DeviceId")
                        .HasDatabaseName("ix_pc_aw_events_device_id");

                    b.HasIndex("EventType")
                        .HasDatabaseName("ix_pc_aw_events_event_type");

                    b.HasIndex("SourceEventId")
                        .HasDatabaseName("ix_pc_aw_events_source_event_id");

                    b.HasIndex("Timestamp")
                        .HasDatabaseName("ix_pc_aw_events_timestamp");

                    b.HasIndex("DeviceId", "BucketId", "SourceEventId")
                        .IsUnique()
                        .HasDatabaseName("ux_pc_aw_events_source")
                        .HasFilter("bucket_id IS NOT NULL AND source_event_id IS NOT NULL");

                    b.ToTable("pc_aw_events");
                });

            modelBuilder.Entity("Pim.Module.PcTracker.Entities.KeystatsAppBreakdownEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("AppName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("app_name");

                    b.Property<long>("DailySnapshotId")
                        .HasColumnType("bigint")
                        .HasColumnName("daily_snapshot_id");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("display_name");

                    b.Property<int>("KeyPresses")
                        .HasColumnType("integer")
                        .HasColumnName("key_presses");

                    b.Property<int>("LeftClicks")
                        .HasColumnType("integer")
                        .HasColumnName("left_clicks");

                    b.Property<int>("MiddleClicks")
                        .HasColumnType("integer")
                        .HasColumnName("middle_clicks");

                    b.Property<int>("RightClicks")
                        .HasColumnType("integer")
                        .HasColumnName("right_clicks");

                    b.Property<double>("ScrollDistance")
                        .HasColumnType("double precision")
                        .HasColumnName("scroll_distance");

                    b.Property<int>("SideBackClicks")
                        .HasColumnType("integer")
                        .HasColumnName("side_back_clicks");

                    b.Property<int>("SideForwardClicks")
                        .HasColumnType("integer")
                        .HasColumnName("side_forward_clicks");

                    b.HasKey("Id");

                    b.HasIndex("DailySnapshotId");

                    b.ToTable("pc_keystats_app_breakdown");
                });

            modelBuilder.Entity("Pim.Module.PcTracker.Entities.KeystatsDailyEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("device_id");

                    b.Property<int>("KeyPresses")
                        .HasColumnType("integer")
                        .HasColumnName("key_presses");

                    b.Property<int>("LeftClicks")
                        .HasColumnType("integer")
                        .HasColumnName("left_clicks");

                    b.Property<int>("MiddleClicks")
                        .HasColumnType("integer")
                        .HasColumnName("middle_clicks");

                    b.Property<double>("MouseDistance")
                        .HasColumnType("double precision")
                        .HasColumnName("mouse_distance");

                    b.Property<int>("PeakCps")
                        .HasColumnType("integer")
                        .HasColumnName("peak_cps");

                    b.Property<int>("PeakKps")
                        .HasColumnType("integer")
                        .HasColumnName("peak_kps");

                    b.Property<int>("RightClicks")
                        .HasColumnType("integer")
                        .HasColumnName("right_clicks");

                    b.Property<double>("ScrollDistance")
                        .HasColumnType("double precision")
                        .HasColumnName("scroll_distance");

                    b.Property<int>("SideBackClicks")
                        .HasColumnType("integer")
                        .HasColumnName("side_back_clicks");

                    b.Property<int>("SideForwardClicks")
                        .HasColumnType("integer")
                        .HasColumnName("side_forward_clicks");

                    b.Property<DateTime>("SnapshotDate")
                        .HasColumnType("date")
                        .HasColumnName("snapshot_date");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId");

                    b.HasIndex("SnapshotDate");

                    b.HasIndex("DeviceId", "SnapshotDate")
                        .IsUnique();

                    b.ToTable("pc_keystats_daily");
                });

            modelBuilder.Entity("Pim.Module.PcTracker.Entities.KeystatsKeyCountEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("Count")
                        .HasColumnType("integer")
                        .HasColumnName("count");

                    b.Property<long>("DailySnapshotId")
                        .HasColumnType("bigint")
                        .HasColumnName("daily_snapshot_id");

                    b.Property<string>("KeyName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("key_name");

                    b.HasKey("Id");

                    b.HasIndex("DailySnapshotId");

                    b.ToTable("pc_keystats_key_counts");
                });

            modelBuilder.Entity("Pim.Module.PcTracker.Entities.KeystatsSampleEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("AppStatsJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("app_stats_json");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("FormattedMouseDistance")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("formatted_mouse_distance");

                    b.Property<string>("FormattedScrollDistance")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("formatted_scroll_distance");

                    b.Property<string>("KeyCountsJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("key_counts_json");

                    b.Property<int>("KeyPresses")
                        .HasColumnType("integer")
                        .HasColumnName("key_presses");

                    b.Property<int>("LeftClicks")
                        .HasColumnType("integer")
                        .HasColumnName("left_clicks");

                    b.Property<int>("MiddleClicks")
                        .HasColumnType("integer")
                        .HasColumnName("middle_clicks");

                    b.Property<double>("MouseDistance")
                        .HasColumnType("double precision")
                        .HasColumnName("mouse_distance");

                    b.Property<int>("PeakCps")
                        .HasColumnType("integer")
                        .HasColumnName("peak_cps");

                    b.Property<int>("PeakKps")
                        .HasColumnType("integer")
                        .HasColumnName("peak_kps");

                    b.Property<string>("PimDeviceId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("pim_device_id");

                    b.Property<string>("RawJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("raw_json");

                    b.Property<int>("RightClicks")
                        .HasColumnType("integer")
                        .HasColumnName("right_clicks");

                    b.Property<DateTimeOffset>("SampledAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sampled_at_utc");

                    b.Property<double>("ScrollDistance")
                        .HasColumnType("double precision")
                        .HasColumnName("scroll_distance");

                    b.Property<int>("SideBackClicks")
                        .HasColumnType("integer")
                        .HasColumnName("side_back_clicks");

                    b.Property<int>("SideForwardClicks")
                        .HasColumnType("integer")
                        .HasColumnName("side_forward_clicks");

                    b.Property<DateTime>("StatsDate")
                        .HasColumnType("date")
                        .HasColumnName("stats_date");

                    b.Property<int>("StatsTimezoneOffsetMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("stats_timezone_offset_minutes");

                    b.HasKey("Id");

                    b.HasIndex("StatsDate")
                        .HasDatabaseName("ix_pc_keystats_samples_stats_date");

                    b.HasIndex("PimDeviceId", "SampledAtUtc")
                        .IsUnique()
                        .HasDatabaseName("ux_pc_keystats_samples_device_minute");

                    b.ToTable("pc_keystats_samples");
                });

            modelBuilder.Entity("Pim.Infrastructure.Data.Entities.LoginAttemptEntity", b =>
                {
                    b.HasOne("Pim.Infrastructure.Data.Entities.UserEntity", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Pim.Infrastructure.Data.Entities.RefreshTokenEntity", b =>
                {
                    b.HasOne("Pim.Infrastructure.Data.Entities.UserEntity", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Pim.Module.Calendar.Entities.EventEntity", b =>
                {
                    b.HasOne("Pim.Module.Calendar.Entities.CalendarEntity", "Calendar")
                        .WithMany("Events")
                        .HasForeignKey("CalendarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Calendar");
                });

            modelBuilder.Entity("Pim.Module.Calendar.Entities.TaskEntity", b =>
                {
                    b.HasOne("Pim.Module.Calendar.Entities.CalendarEntity", "Calendar")
                        .WithMany("Tasks")
                        .HasForeignKey("CalendarId");

                    b.HasOne("Pim.Module.Calendar.Entities.TaskEntity", "ParentTask")
                        .WithMany("SubTasks")
                        .HasForeignKey("ParentTaskId");

                    b.Navigation("Calendar");

                    b.Navigation("ParentTask");
                });

            modelBuilder.Entity("Pim.Module.PcTracker.Entities.KeystatsAppBreakdownEntity", b =>
                {
                    b.HasOne("Pim.Module.PcTracker.Entities.KeystatsDailyEntity", "DailySnapshot")
                        .WithMany("AppBreakdowns")
                        .HasForeignKey("DailySnapshotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DailySnapshot");
                });

            modelBuilder.Entity("Pim.Module.PcTracker.Entities.KeystatsKeyCountEntity", b =>
                {
                    b.HasOne("Pim.Module.PcTracker.Entities.KeystatsDailyEntity", "DailySnapshot")
                        .WithMany("KeyCounts")
                        .HasForeignKey("DailySnapshotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DailySnapshot");
                });

            modelBuilder.Entity("Pim.Module.Calendar.Entities.CalendarEntity", b =>
                {
                    b.Navigation("Events");

                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("Pim.Module.Calendar.Entities.TaskEntity", b =>
                {
                    b.Navigation("SubTasks");
                });

            modelBuilder.Entity("Pim.Module.PcTracker.Entities.KeystatsDailyEntity", b =>
                {
                    b.Navigation("AppBreakdowns");

                    b.Navigation("KeyCounts");
                });
#pragma warning restore 612, 618
        }
    }
}
