<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\Pim.Core\Pim.Core.csproj" />
    <ProjectReference Include="..\Pim.Infrastructure\Pim.Infrastructure.csproj" />
    <ProjectReference Include="..\modules\Pim.Module.Calendar\Pim.Module.Calendar.csproj" />
    <ProjectReference Include="..\modules\Pim.Module.PcTracker\Pim.Module.PcTracker.csproj" />
    <ProjectReference Include="..\modules\Pim.Module.QuickNotes\Pim.Module.QuickNotes.csproj" />
    <ProjectReference Include="..\modules\Pim.Module.Files\Pim.Module.Files.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.11">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Serilog.AspNetCore" Version="10.0.0" />
    <PackageReference Include="Serilog.Formatting.Compact" Version="3.0.0" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

</Project>
