<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\Pim.Core\Pim.Core.csproj" />
    <ProjectReference Include="..\Pim.Infrastructure\Pim.Infrastructure.csproj" />
    <ProjectReference Include="..\modules\Pim.Module.Calendar\Pim.Module.Calendar.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

</Project>
