CREATE TABLE IF NOT EXISTS pc_keystats_daily (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    device_id varchar(64) NOT NULL,
    snapshot_date date NOT NULL,
    key_presses integer NOT NULL DEFAULT 0,
    left_clicks integer NOT NULL DEFAULT 0,
    right_clicks integer NOT NULL DEFAULT 0,
    middle_clicks integer NOT NULL DEFAULT 0,
    side_back_clicks integer NOT NULL DEFAULT 0,
    side_forward_clicks integer NOT NULL DEFAULT 0,
    mouse_distance double precision NOT NULL DEFAULT 0,
    scroll_distance double precision NOT NULL DEFAULT 0,
    peak_kps integer NOT NULL DEFAULT 0,
    peak_cps integer NOT NULL DEFAULT 0,
    created_at timestamp with time zone NOT NULL DEFAULT NOW(),
    UNIQUE(device_id, snapshot_date)
);
CREATE INDEX IF NOT EXISTS ix_pc_keystats_daily_device_id ON pc_keystats_daily(device_id);
CREATE INDEX IF NOT EXISTS ix_pc_keystats_daily_snapshot_date ON pc_keystats_daily(snapshot_date);

CREATE TABLE IF NOT EXISTS pc_keystats_key_counts (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    daily_snapshot_id bigint NOT NULL REFERENCES pc_keystats_daily(id) ON DELETE CASCADE,
    key_name varchar(128) NOT NULL,
    count integer NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS pc_keystats_app_breakdown (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    daily_snapshot_id bigint NOT NULL REFERENCES pc_keystats_daily(id) ON DELETE CASCADE,
    app_name varchar(256) NOT NULL,
    display_name varchar(512) NOT NULL DEFAULT '',
    key_presses integer NOT NULL DEFAULT 0,
    left_clicks integer NOT NULL DEFAULT 0,
    right_clicks integer NOT NULL DEFAULT 0,
    middle_clicks integer NOT NULL DEFAULT 0,
    side_back_clicks integer NOT NULL DEFAULT 0,
    side_forward_clicks integer NOT NULL DEFAULT 0,
    scroll_distance double precision NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS pc_aw_events (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    device_id varchar(64) NOT NULL,
    "timestamp" timestamp with time zone NOT NULL,
    duration double precision NOT NULL DEFAULT 0,
    event_type varchar(16) NOT NULL DEFAULT 'window',
    app_name varchar(256),
    window_title text,
    afk_status varchar(16),
    created_at timestamp with time zone NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS ix_pc_aw_events_device_id ON pc_aw_events(device_id);
CREATE INDEX IF NOT EXISTS ix_pc_aw_events_timestamp ON pc_aw_events("timestamp");
CREATE INDEX IF NOT EXISTS ix_pc_aw_events_event_type ON pc_aw_events(event_type);

-- Seed sample Keystats data (idempotent: delete then insert)
DELETE FROM pc_keystats_key_counts WHERE daily_snapshot_id IN (SELECT id FROM pc_keystats_daily WHERE device_id = 'pc-dev-001' AND snapshot_date = '2026-05-16');
DELETE FROM pc_keystats_app_breakdown WHERE daily_snapshot_id IN (SELECT id FROM pc_keystats_daily WHERE device_id = 'pc-dev-001' AND snapshot_date = '2026-05-16');
DELETE FROM pc_aw_events WHERE device_id = 'pc-dev-001';
DELETE FROM pc_keystats_daily WHERE device_id = 'pc-dev-001' AND snapshot_date = '2026-05-16';

INSERT INTO pc_keystats_daily (device_id, snapshot_date, key_presses, left_clicks, right_clicks, middle_clicks, side_back_clicks, side_forward_clicks, mouse_distance, scroll_distance, peak_kps, peak_cps)
VALUES ('pc-dev-001', '2026-05-16', 6421, 3250, 72, 15, 8, 3, 3243110.72, 7859, 11, 4);

-- Seed key counts
INSERT INTO pc_keystats_key_counts (daily_snapshot_id, key_name, count)
SELECT id, 'Space', 473 FROM pc_keystats_daily WHERE device_id = 'pc-dev-001' AND snapshot_date = '2026-05-16';
INSERT INTO pc_keystats_key_counts (daily_snapshot_id, key_name, count)
SELECT id, 'Backspace', 605 FROM pc_keystats_daily WHERE device_id = 'pc-dev-001' AND snapshot_date = '2026-05-16';
INSERT INTO pc_keystats_key_counts (daily_snapshot_id, key_name, count)
SELECT id, 'A', 410 FROM pc_keystats_daily WHERE device_id = 'pc-dev-001' AND snapshot_date = '2026-05-16';
INSERT INTO pc_keystats_key_counts (daily_snapshot_id, key_name, count)
SELECT id, 'LCtrl', 160 FROM pc_keystats_daily WHERE device_id = 'pc-dev-001' AND snapshot_date = '2026-05-16';
INSERT INTO pc_keystats_key_counts (daily_snapshot_id, key_name, count)
SELECT id, 'Enter', 155 FROM pc_keystats_daily WHERE device_id = 'pc-dev-001' AND snapshot_date = '2026-05-16';
INSERT INTO pc_keystats_key_counts (daily_snapshot_id, key_name, count)
SELECT id, 'Ctrl+C', 48 FROM pc_keystats_daily WHERE device_id = 'pc-dev-001' AND snapshot_date = '2026-05-16';

-- Seed app breakdown
INSERT INTO pc_keystats_app_breakdown (daily_snapshot_id, app_name, display_name, key_presses, left_clicks, right_clicks, middle_clicks, side_back_clicks, side_forward_clicks, scroll_distance)
SELECT id, 'Code', 'Visual Studio Code', 1830, 1500, 30, 5, 2, 1, 2340 FROM pc_keystats_daily WHERE device_id = 'pc-dev-001' AND snapshot_date = '2026-05-16';
INSERT INTO pc_keystats_app_breakdown (daily_snapshot_id, app_name, display_name, key_presses, left_clicks, right_clicks, middle_clicks, side_back_clicks, side_forward_clicks, scroll_distance)
SELECT id, 'chrome', 'Google Chrome', 2085, 878, 20, 8, 4, 1, 3456 FROM pc_keystats_daily WHERE device_id = 'pc-dev-001' AND snapshot_date = '2026-05-16';
INSERT INTO pc_keystats_app_breakdown (daily_snapshot_id, app_name, display_name, key_presses, left_clicks, right_clicks, middle_clicks, side_back_clicks, side_forward_clicks, scroll_distance)
SELECT id, 'WindowsTerminal', 'Windows Terminal', 834, 330, 8, 0, 0, 0, 567 FROM pc_keystats_daily WHERE device_id = 'pc-dev-001' AND snapshot_date = '2026-05-16';

-- Seed AW events (window events for today)
INSERT INTO pc_aw_events (device_id, "timestamp", duration, event_type, app_name, window_title) VALUES
('pc-dev-001', '2026-05-16 06:30:00+00', 360, 'window', 'chrome', 'GitHub - PIM Project Dashboard'),
('pc-dev-001', '2026-05-16 06:36:00+00', 120, 'window', 'WindowsTerminal', 'Windows PowerShell'),
('pc-dev-001', '2026-05-16 06:38:00+00', 2400, 'window', 'Code', 'PcTrackerModule.cs — PIM'),
('pc-dev-001', '2026-05-16 07:18:00+00', 180, 'window', 'chrome', 'Stack Overflow - C# EF Core'),
('pc-dev-001', '2026-05-16 07:21:00+00', 3600, 'window', 'Code', 'PcTrackerService.cs — PIM'),
('pc-dev-001', '2026-05-16 08:21:00+00', 900, 'window', 'chrome', 'Gmail - Inbox'),
('pc-dev-001', '2026-05-16 08:36:00+00', 4500, 'window', 'Code', 'PcTrackerPage.tsx — PIM'),
('pc-dev-001', '2026-05-16 09:51:00+00', 600, 'window', 'WindowsTerminal', 'dotnet run'),
('pc-dev-001', '2026-05-16 10:01:00+00', 1800, 'window', 'chrome', 'Microsoft Teams'),
('pc-dev-001', '2026-05-16 10:31:00+00', 1200, 'window', 'Code', 'TrayIcon.cs — PIM'),
('pc-dev-001', '2026-05-16 10:51:00+00', 360, 'window', 'chrome', 'Claude Code - Session'),
('pc-dev-001', '2026-05-16 10:57:00+00', 4800, 'window', 'Code', 'AppLayout.tsx — PIM'),
('pc-dev-001', '2026-05-16 12:17:00+00', 360, 'window', 'chrome', 'Lunch break browsing'),
('pc-dev-001', '2026-05-16 13:30:00+00', 7200, 'window', 'Code', 'EntityConfigurations.cs — PIM'),
('pc-dev-001', '2026-05-16 15:30:00+00', 600, 'window', 'chrome', 'Confluence - PIM Docs'),
('pc-dev-001', '2026-05-16 15:40:00+00', 3600, 'window', 'Code', 'Sidebar.tsx — PIM');

CREATE TABLE IF NOT EXISTS pc_app_categories (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    app_pattern VARCHAR(128) NOT NULL,
    category_name VARCHAR(64) NOT NULL,
    color VARCHAR(7) DEFAULT '#6B5EE4',
    priority INT DEFAULT 0,
    is_builtin BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_pc_app_categories_app_pattern ON pc_app_categories(app_pattern);

INSERT INTO pc_app_categories (app_pattern, category_name, color, priority, is_builtin) VALUES
('Code', '编程', '#6B5EE4', 100, TRUE),
('Visual Studio', '编程', '#6B5EE4', 100, TRUE),
('VS Code', '编程', '#6B5EE4', 100, TRUE),
('Rider', '编程', '#6B5EE4', 100, TRUE),
('vim', '编程', '#6B5EE4', 90, TRUE),
('nvim', '编程', '#6B5EE4', 90, TRUE),
('chrome', '浏览', '#0EA8A0', 100, TRUE),
('msedge', '浏览', '#0EA8A0', 100, TRUE),
('firefox', '浏览', '#0EA8A0', 100, TRUE),
('Arc', '浏览', '#0EA8A0', 100, TRUE),
('Brave', '浏览', '#0EA8A0', 100, TRUE),
('WeChat', '沟通', '#F5935A', 100, TRUE),
('微信', '沟通', '#F5935A', 100, TRUE),
('DingTalk', '沟通', '#F5935A', 100, TRUE),
('钉钉', '沟通', '#F5935A', 100, TRUE),
('QQ', '沟通', '#F5935A', 100, TRUE),
('Telegram', '沟通', '#F5935A', 100, TRUE),
('Slack', '沟通', '#F5935A', 100, TRUE),
('Discord', '沟通', '#F5935A', 100, TRUE),
('WindowsTerminal', '终端', '#E05A7A', 100, TRUE),
('Terminal', '终端', '#E05A7A', 100, TRUE),
('cmd', '终端', '#E05A7A', 100, TRUE),
('PowerShell', '终端', '#E05A7A', 100, TRUE),
('Alacritty', '终端', '#E05A7A', 90, TRUE),
('iTerm2', '终端', '#E05A7A', 90, TRUE),
('explorer', '文件管理', '#3B82F6', 100, TRUE),
('Finder', '文件管理', '#3B82F6', 100, TRUE),
('TotalCommander', '文件管理', '#3B82F6', 90, TRUE),
('Everything', '文件管理', '#3B82F6', 90, TRUE),
('Spotify', '音乐', '#10B981', 100, TRUE),
('Netease', '音乐', '#10B981', 90, TRUE),
('foobar2000', '音乐', '#10B981', 90, TRUE),
('Word', '办公', '#F59E0B', 100, TRUE),
('Excel', '办公', '#F59E0B', 100, TRUE),
('PowerPoint', '办公', '#F59E0B', 100, TRUE),
('Notion', '办公', '#F59E0B', 90, TRUE),
('Obsidian', '办公', '#F59E0B', 90, TRUE),
('Typora', '办公', '#F59E0B', 90, TRUE)
ON CONFLICT (app_pattern) DO NOTHING;
